export const CREATE_SETTLEMENT = "create_settlement"

export const SETTLEMENT_REQUESTED = "SETTLEMENT_REQUESTED"
export const SETTLEMENT_REQUEST_SUCCESS = 'SETTLEMENT_REQUEST_SUCCESS'

export const SETTLEMENT_LIST_REQUESTED = 'SETTLEMENT_LIST_REQUESTED'
export const SETTLEMENT_LIST_REQUEST_SUCCESS = 'SETTLEMENT_LIST_REQUEST_SUCCESS'

export const SETTLEMENT_UPDATED = 'SETTLEMENT_UPDATED'
